Repository Summer-Bootcamp-2024/SML-Frontend, pull requests merged in 2024-07, with the labels that each got.

#2 [Chore]환경설정 재설치
  .eslintrc.cjs
  .gitignore
  .prettierrc.json
  index.html
  package.json
  postcss.config.cjs
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/index.css
  src/main.jsx
  tailwind.config.js
  vite.config.js
  yarn.lock
Labels: 기타/세팅

#5 Design : 로그인 페이지 퍼블리싱
  README.md
  package.json
  src/App.css
  src/App.jsx
  src/components/Button.jsx
  src/components/network.json
  src/pages/Login.jsx
  tailwind.config.js
  yarn.lock
Labels: 디자인

#9 [Design]온보딩 페이지 퍼블리싱
  package.json
  src/App.jsx
  src/assets/images/mainthird.png
  src/assets/images/profile.png
  src/components/Logolottie.jsx
  src/components/logo.json
  src/components/main/Creditlottie.jsx
  src/components/main/Firstlottie.jsx
  src/components/main/Header.jsx
  src/components/main/Mainfirst.jsx
  src/components/main/Mainsecond.jsx
  src/components/main/Mainthird.jsx
  src/components/main/credit.json
  src/components/main/first.json
  src/pages/MainPage.jsx
  tailwind.config.js
  yarn.lock
Labels: 디자인

#13 Design : 사이드바 퍼블리싱
  src/App.jsx
  src/assets/images/profileImg.png
  src/components/Sidebar.jsx
  src/pages/LoginPage.jsx
  src/pages/Mypage.jsx
  src/pages/SignupPage.jsx
Labels: 디자인

#15 Design: 마이페이지 퍼블리싱
  src/App.jsx
  src/assets/images/profileImgSquare.png
  src/components/Button.jsx
  src/components/Sidebar.jsx
  src/pages/Mypage.jsx
  src/pages/MypageEdit.jsx
Labels: 디자인

#17 [Design] 일촌 목록 페이지 퍼블리싱
  src/App.jsx
  src/assets/images/profileImg2.png
  src/components/FriendGraph.jsx
  src/components/FriendList.jsx
  src/components/ProfileModal.jsx
  src/components/Sidebar.jsx
  src/pages/FriendListPage.jsx
  tailwind.config.js
Labels: 디자인

#20 [Design]일촌목록 그래프 퍼블리싱
  package.json
  src/App.jsx
  src/assets/images/mainsecond.png
  src/assets/images/myprofile/profileImg.png
  src/assets/images/myprofile/profileImgSquare.png
  src/components/FriendGraph.jsx
  src/components/ProfileModal.jsx
  src/components/Sidebar.jsx
  src/components/main/Mainsecond.jsx
  src/pages/Mypage.jsx
  yarn.lock
Labels: 디자인

#21 [Design] 채팅 페이지 퍼블리싱
  src/App.jsx
  src/assets/images/sendimg.png
  src/pages/ChatpPage.jsx
Labels: 디자인

#22 Design/#16
  src/App.jsx
  src/components/Button.jsx
  src/components/ChargeModal.jsx
  src/components/Credit.jsx
  src/components/ProfileModal.jsx
  src/components/ProfileSlide.jsx
  src/components/search/ProfileCard.jsx
  src/components/search/ProfileDetail.jsx
  src/components/search/ProfileImg.jsx
  src/components/search/ProfileList.jsx
  src/components/search/SearchBar.jsx
  src/components/search/SearchCon.jsx
  src/pages/ChatpPage.jsx
  src/pages/MypageEdit.jsx
  src/pages/SearchPage.jsx
  src/pages/SearchPageMain.jsx
Labels: 디자인

#24 [Design] 검색페이지 css 수정
  src/components/ChargeModal.jsx
  src/components/CreditModal.jsx
  src/components/search/ProfileCard.jsx
  src/components/search/ProfileList.jsx
  src/components/search/SearchBar.jsx
  src/components/search/SearchCon.jsx
  src/components/search/profile/ProfileCard.jsx
  src/components/search/profile/ProfileDetail.jsx
  src/components/search/profile/ProfileImg.jsx
  src/components/search/profile/ProfileList.jsx
  src/components/search/profile/ProfileSlide.jsx
  src/pages/ChatpPage.jsx
  src/pages/Mypage.jsx
  src/pages/MypageEdit.jsx
  src/pages/SearchPage.jsx
  src/pages/SearchPageMain.jsx
Labels: 디자인, 에러해결

#33 [#32]Feat : 로그아웃 api 연동
  src/App.jsx
  src/components/Sidebar.jsx
  src/pages/LoginPage.jsx
Labels: 기능구현

#34 [Feat] 일촌목록 조회 API 연동
  src/App.jsx
  src/components/FriendList.jsx
  src/components/ProfileModal.jsx
  src/pages/FriendListPage.jsx
  src/pages/LoginPage.jsx
  src/store/store.js
Labels: 기능구현

#37 [Design] 일촌목록에서 소개받기 모달 추가 퍼블리싱
  src/components/FriendGraph.jsx
  src/components/FriendList.jsx
  src/components/ProfileModal.jsx
  src/pages/FriendListPage.jsx
Labels: 디자인

#38 [feat] 일촌 요청/수락/거절 api 연동
  src/components/chat/Chat.jsx
  src/components/chat/ChatRoom.jsx
  src/pages/ChatpPage.jsx
Labels: 기능구현

#40 feat: user_id zustand로 상태관리
  src/App.jsx
  src/components/FriendList.jsx
  src/pages/LoginPage.jsx
  src/store/store.js
Labels: 기능구현

#45 [design]채팅 퍼블리싱 수정
  src/components/chat/Chat.jsx
Labels: 디자인

#47 Feat/#31
  src/components/Sidebar.jsx
  src/pages/FriendListPage.jsx
  src/pages/LoginPage.jsx
  src/pages/Mypage.jsx
  src/pages/SignupPage.jsx
  src/store/store.js
Labels: 기능구현, 리팩토링

#48 [error] localstorage에 user_id 저장하여 에러 해결
  src/components/Sidebar.jsx
  src/store/store.js
Labels: 에러해결

#42 [Feat]일촌 삭제 api 연동
  src/components/FriendList.jsx
  src/components/ProfileModal.jsx
  src/pages/FriendListPage.jsx
Labels: 기능구현, 디자인

#50 [#49]Fix : user_id 안뜨는 문제 해결
  src/pages/LoginPage.jsx
  src/pages/Mypage.jsx
Labels: 에러해결

#52 [#51]Feat : 프로필 수정 api 연동, 충전하기 모달 창 띄우기 완료
  src/assets/images/myprofile/basicProfile.png
  src/components/Sidebar.jsx
  src/pages/Mypage.jsx
  src/pages/MypageEdit.jsx
Labels: 기능구현

#53 [feat] 일촌 관계도 그래프 구현
  src/components/FriendGraph.jsx
  src/pages/FriendListPage.jsx
Labels: 기능구현

#57 [#56]Design : 검색 페이지 퍼블리싱 수정, 모달 위치 수정
  src/components/CreditModal.jsx
  src/components/search/profile/ProfileSlide.jsx
  src/pages/SearchPage.jsx
Labels: 기능구현, 리팩토링

#58 [Feat/#55] 채팅방 조회 api 연동
  src/components/chat/Chat.jsx
  src/components/chat/ChatRoom.jsx
  src/pages/ChatpPage.jsx
Labels: 기능구현

#65 [Feat/#61]채팅기능 구현
  src/components/chat/Chat.jsx
  src/components/chat/ChatRoom.jsx
  src/pages/ChatpPage.jsx
Labels: 기능구현

#66 [#64]Feat : 충전하기 api 연동
  src/components/ChargeModal.jsx
  src/components/CreditModal.jsx
  src/pages/Mypage.jsx
Labels: 기능구현, 에러해결

#70 [Feat/#61] 채팅방생성, 소개하기 요청, 일촌 요청 api 연동
  src/components/FriendList.jsx
  src/components/chat/Chat.jsx
  src/components/chat/ChatRoom.jsx
  src/pages/ChatpPage.jsx
Labels: 기능구현, 에러해결

#72 Feat/#63
  src/App.jsx
  src/components/CreditModal.jsx
  src/components/search/SearchBar.jsx
  src/components/search/profile/ProfileCard.jsx
  src/components/search/profile/ProfileDetail.jsx
  src/components/search/profile/ProfileImg.jsx
  src/components/search/profile/ProfileList.jsx
  src/components/search/profile/ProfileSlide.jsx
  src/pages/SearchPage.jsx
  src/pages/SearchPageMain.jsx
Labels: 기능구현, 에러해결

#74 [Design/#69] 폰트적용
  src/components/ChargeModal.jsx
  src/components/CreditModal.jsx
  src/components/ProfileModal.jsx
  src/components/Sidebar.jsx
  src/components/chat/Chat.jsx
  src/components/chat/ChatRoom.jsx
  src/components/main/Header.jsx
  src/components/main/Mainfirst.jsx
  src/components/main/Mainsecond.jsx
  src/components/main/Mainthird.jsx
  src/components/search/profile/ProfileSlide.jsx
  src/index.css
  src/main.jsx
  src/pages/FriendListPage.jsx
  src/pages/LoginPage.jsx
  src/pages/Mypage.jsx
  src/pages/MypageEdit.jsx
  src/pages/SearchPage.jsx
  src/pages/SearchPageMain.jsx
  src/pages/SignupPage.jsx
Labels: 디자인

#75 [#73] 채팅방 생성 api 연동
  src/components/CreditModal.jsx
  src/components/search/profile/ProfileList.jsx
  src/components/search/profile/ProfileSlide.jsx
  src/pages/SearchPage.jsx
  src/store/store.js
Labels: 기능구현

#77 [#76]Feat : 소개 요청 api 연동
  src/components/CreditModal.jsx
  src/components/search/profile/ProfileSlide.jsx
  src/pages/SearchPage.jsx
  src/store/store.js
Labels: 기능구현

#80 Feat : s3 연동
  package.json
  src/components/Sidebar.jsx
  src/components/chat/Chat.jsx
  src/pages/Mypage.jsx
  src/pages/MypageEdit.jsx
  yarn.lock
Labels: 기능구현

#84 Feat/#78 선물하기 api 연동
  src/components/FriendList.jsx
  src/components/GiftCreditModal.jsx
  src/components/ProfileModal.jsx
  src/components/chat/Chat.jsx
  src/components/search/profile/ProfileSlide.jsx
  src/pages/ChatpPage.jsx
  src/pages/SearchPage.jsx
  src/pages/SearchPageMain.jsx
Labels: 기능구현

#82 [Feat/#68] 소개요청 api response값으로 수정
  src/components/CreditModal.jsx
  src/components/Sidebar.jsx
  src/components/chat/Chat.jsx
  src/components/chat/ChatRoom.jsx
  src/pages/ChatpPage.jsx
  src/store/store.js
Labels: 기능구현, 리팩토링

#85 Feat/#81 선물 기록 api 연동
  src/pages/LoginPage.jsx
  src/pages/Mypage.jsx
Labels: 기능구현

#88 [chore/#87] Dockerfile.prod 추가
  Dockerfile.prod
Labels: 기타/세팅

#89 [#86]Error : 컴파일 에러 해결
  src/components/CreditModal.jsx
  src/components/GiftCreditModal.jsx
  src/components/chat/Chat.jsx
Labels: 에러해결

#91 [chore/#83] yarn build 시 발생하는 에러 및 주의사항 해결
  vite.config.js
Labels: 기타/세팅

#94 [Design/#71] 회원가입/로그인 모달창 추가, 회원가입/마이페이지 selectbox 추가
  src/components/check.json
  src/components/checklottie.jsx
  src/components/fail.json
  src/components/faillottie.jsx
  src/components/modal/LoginModal.jsx
  src/components/modal/SignUpModal.jsx
  src/pages/LoginPage.jsx
  src/pages/Mypage.jsx
  src/pages/MypageEdit.jsx
  src/pages/SignupPage.jsx
Labels: 디자인

#97 Design/#90 UI 수정
  src/components/CreditModal.jsx
  src/components/Sidebar.jsx
  src/components/search/profile/ProfileCard.jsx
  src/components/search/profile/ProfileList.jsx
  src/components/search/profile/ProfileSlide.jsx
  src/pages/SearchPage.jsx
Labels: 디자인

#95 [refactor/#93] 디렉토리 구조 변경
  src/components/friend/FriendGraph.jsx
  src/components/friend/FriendList.jsx
  src/components/lottie/Creditlottie.jsx
  src/components/lottie/Firstlottie.jsx
  src/components/lottie/Logolottie.jsx
  src/components/lottie/check.json
  src/components/lottie/checklottie.jsx
  src/components/lottie/credit.json
  src/components/lottie/fail.json
  src/components/lottie/faillottie.jsx
  src/components/lottie/first.json
  src/components/lottie/logo.json
  src/components/lottie/network.json
  src/components/main/Header.jsx
  src/components/main/Mainfirst.jsx
  src/components/main/Mainsecond.jsx
  src/components/modal/ChargeModal.jsx
  src/components/modal/CreditModal.jsx
  src/components/modal/GiftCreditModal.jsx
  src/components/modal/LoginModal.jsx
  src/components/modal/ProfileModal.jsx
  src/components/modal/SignUpModal.jsx
  src/pages/ChatpPage.jsx
  src/pages/FriendListPage.jsx
  src/pages/LoginPage.jsx
  src/pages/Mypage.jsx
  src/pages/SearchPage.jsx
  vite.config.js
Labels: 리팩토링

#98 [Design/#96] 검색페이지 필터링 category 추가 & category/job 내용 추가
  src/components/search/SearchBar.jsx
  src/pages/FriendListPage.jsx
  src/pages/Mypage.jsx
  src/pages/MypageEdit.jsx
  src/pages/SearchPage.jsx
  src/pages/SignupPage.jsx
Labels: 디자인

#102 [#101]Design : 마이페이지 수정
  src/components/modal/CreditModal.jsx
  src/pages/Mypage.jsx
  src/pages/MypageEdit.jsx
Labels: 디자인

#106 [Error/#105] 일촌관계/소개요청 에러 해결
  src/components/chat/Chat.jsx
  src/components/chat/ChatRoom.jsx
  src/components/lottie/faillottie.jsx
  src/components/modal/FriendRequestModal.jsx
  src/components/modal/GettingIntroduceModal.jsx
  src/components/modal/IntroduceFriendModal.jsx
  src/components/modal/LoginModal.jsx
  src/pages/ChatpPage.jsx
Labels: 디자인, 에러해결

#108 [Error/#107] 그래프 관계도에서 프로필 조회 안되는 에러 해결
  src/components/friend/FriendGraph.jsx
  src/components/modal/ProfileModal.jsx
  src/components/search/profile/ProfileSlide.jsx
Labels: 디자인, 에러해결

#110 [#103]Design: 로그아웃 모달 수정
  src/components/Sidebar.jsx
  src/components/modal/LogoutModal.jsx
Labels: 디자인

#120 [#119]Design : 프로필 사진 크기 수정
  src/components/Sidebar.jsx
  src/pages/Mypage.jsx
  src/pages/MypageEdit.jsx
Labels: 디자인

#121 [#112]Refactor : 코드 리팩토링
  src/components/Sidebar.jsx
  src/components/chat/Chat.jsx
  src/components/chat/ChatRoom.jsx
  src/components/modal/ChargeModal.jsx
  src/components/modal/CreditModal.jsx
  src/components/modal/FriendRequestModal.jsx
  src/components/modal/GettingIntroduceModal.jsx
  src/components/modal/GiftCreditModal.jsx
  src/components/modal/IntroduceFriendModal.jsx
  src/components/modal/ProfileModal.jsx
  src/components/search/SearchBar.jsx
  src/components/search/profile/ProfileCard.jsx
  src/components/search/profile/ProfileImg.jsx
  src/components/search/profile/ProfileSlide.jsx
  src/pages/LoginPage.jsx
  src/pages/Mypage.jsx
  src/pages/MypageEdit.jsx
  src/pages/SearchPage.jsx
  src/pages/SignupPage.jsx
  src/store/store.js
Labels: 리팩토링

#122 [Design/#111] UI/UX 수정
  src/assets/images/credit/credit10000.png
  src/assets/images/credit/credit15000.png
  src/assets/images/credit/credit20000.png
  src/assets/images/credit/credit5000.png
  src/components/Sidebar.jsx
  src/components/chat/Chat.jsx
  src/components/friend/FriendGraph.jsx
  src/components/friend/FriendList.jsx
  src/components/main/Header.jsx
  src/components/modal/ChargeModal.jsx
  src/components/modal/GiftCreditModal.jsx
  src/components/modal/LoginModal.jsx
  src/components/modal/ProfileModal.jsx
  src/components/search/SearchBar.jsx
  src/components/search/profile/ProfileSlide.jsx
  src/pages/FriendListPage.jsx
  src/pages/LoginPage.jsx
  src/pages/Mypage.jsx
  src/pages/SearchPage.jsx
  src/pages/SignupPage.jsx
Labels: 디자인

#124 [#115]Refactor : 사이드바 캐싱 처리
  src/components/Sidebar.jsx
Labels: 리팩토링

#125 [Design/#123] toast 알림 구현
  package.json
  src/components/chat/Chat.jsx
  src/components/modal/FriendRequestModal.jsx
  src/components/modal/GiftCreditModal.jsx
  src/components/modal/IntroduceFriendModal.jsx
  src/pages/ChatpPage.jsx
  yarn.lock
Labels: 기능구현, 디자인

#127 [Design/#126] 로고 변경
  src/assets/images/LogoImg.png
  src/assets/images/sidebarLogo.png
  src/components/Sidebar.jsx
  src/components/main/Header.jsx
Labels: 디자인

#130 [#129]Error : 사이드바 프로필 에러 수정
  src/components/Sidebar.jsx
  src/pages/Mypage.jsx
Labels: 에러해결

#133 [#132]Design : 검색 페이지 UI 수정
  src/components/search/profile/ProfileSlide.jsx
  src/pages/SearchPage.jsx
  src/store/store.js
Labels: 디자인

#134 [Feat/#131] 그래프 노드 이미지url 변경
  src/components/friend/FriendGraph.jsx
Labels: 기능구현
